version: "3.9"
services:
  app:
    build: .
    ports: ["3000:3000"]
    environment:
      SESSION_PASSWORD: "dev_super_secret_change_me_32_chars_min"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm","dev"]
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pestpro
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
